default_platform :ios

platform :ios do
    desc "SwiftLint autocorrect"
    lane :lint_autocorrect do 
        swiftlint(
            mode: :autocorrect,
            config_file: ".swiftlint.yml",
            ignore_exit_status: true
        )
    end
end
