name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  create_rc_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Create RC branch and bump up version
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git switch -c rc-${{ github.event.inputs.version }}
        echo "test" > ${{ github.event.inputs.version }}
        git add .
        git commit -m "bump up version"
        git push origin HEAD
