name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "release version -> ${{ github.event.inputs.version }}!"
        git status
        git branch
        git switch -c rc-${{ github.event.inputs.version }}!
        git branch
        git push origin HEAD
        
