name: Mint
on:
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Swift
      uses: fwal/setup-swift@v1

    - name: Check version
      run: swift --version

    - name: Install Mint
      run: | 
        git clone https://github.com/yonaskolb/Mint.git
        cd Mint
        swift run mint install yonaskolb/mint

    - name: Install RIBsTreeMaker
      run: mint install imairi/RIBsTreeMaker

    - name: Check RIBsTreeMaker
      run: RIBsTreeMaker
