name: Mint
on:
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".plantuml"
    steps:
    - name: Set up Swift
      uses: fwal/setup-swift@v1

    - name: Check version
      run: swift --version

    - name: Install RIBsTreeMaker
      run: |
        git clone https://github.com/imairi/RIBsTreeMaker.git
        cd RIBsTreeMaker
        swift run RIBsTreeMaker
        cd -

    - name: Checkout Source 
      uses: actions/checkout@v1

    - name: plantuml
      uses: grassedge/generate-plantuml-action@master
      with:
        path: uml
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Get changed UML files
#      id: getfile
#      run: |
#        echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
#    - name: UML files considered echo output
#      run: |
#        echo ${{ steps.getfile.outputs.files }}
#    - name: Generate SVG Diagrams
#      uses: cloudbees/plantuml-github-action@master
#      with:
#          args: -v -tsvg ${{ steps.getfile.outputs.files }}
#    - name: Generate PNG Diagrams
#      uses: cloudbees/plantuml-github-action@master
#      with:
#          args: -v -tpng ${{ steps.getfile.outputs.files }}
#    - name: Push Local Changes
#      uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
#      with: 
#        commit_user_name: "my user name"
#        commit_user_email: "me@email.org"
#        commit_author: "My User <me@email.org>"
#        commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
#        branch: ${{ github.head_ref }}
