name: Mint
on:
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Swift
      uses: fwal/setup-swift@v1

    - name: Check version
      run: swift --version

    - name: Install RIBsTreeMaker
      run: |
        git clone https://github.com/imairi/RIBsTreeMaker.git
        cd RIBsTreeMaker
        swift run RIBsTreeMaker

    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: uml
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
