name: Slack
on:
  workflow_dispatch:

jobs:
  create_rc_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
      with:
        text: <!subteam^S01198M56L8> succeeded.
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "Workflow",
                  "value": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                },
                {
                  "title": "Info.plist",
                  "value": "${{ github.event.repository.html_url }}/blob/master/Info.plist"
                }
              ]
            }
          ]
