name: SwiftLint 
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: master 

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache Bundle
        uses: actions/cache@v2
        id: cache-bundle
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: SwiftLint
        run: |
          pwd
          cd ~
          pwd
          git clone https://github.com/realm/SwiftLint
          cd SwiftLint
          make
          cd ~/repo
          ~/SwiftLint/.build/x86_64-unknown-linux/release/swiftlint --config ./.swiftlint/swiftlint.yml
