name: SwiftLint 
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: master 

      - name: GitHub Action for SwiftLint
        uses: imairi/action-swiftlint@3.2.0
