name: SwiftLint 
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master 

      - name: SwifntLint autocorrect
        id: run-swiftlint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: autocorrect

      - name: Check diff
        if: steps.run-swiftlint.conclusion == 'success'
        run: |
          git status
          echo "- - - -"
          git branch
          echo "- - - -"
          git reflog
          if git diff-index --quiet HEAD; then
            echo "HAS_DIFF=false" >> $GITHUB_ENV
          else
            echo "HAS_DIFF=true" >> $GITHUB_ENV
          fi
        env:
          HAS_DIFF: false

      - name: Set 
        run: |
          echo "::set-output name=FOO::false"
        id: step-foo

      - name: Get
        if: ${{ steps.step-foo.outputs.FOO }} == 'true'
        run: |
          echo 'The FOO is' ${{ steps.step-foo.outputs.FOO }}
      
      - name: Create Pull Request
        if: ${{ env.HAS_DIFF }}
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: swiftlint-autocorrect-${{ github.run_number }}
          commit-message: swiftlint autocorrect
          title: SwiftLint autocorrect
          body: |
            Modified swift files following swiftlint rules.
            These changes are automattically commited from GitHub Actions.
