name: Trigger test
on:
  pull_request:
    types: [closed]

jobs:
  trigger_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Echo
      run: |
        echo ${{ github.event.pull_request }}
        echo ${{ github.event.pull_request.merged }}
    - name: Echo
      if: github.event.pull_request.merged == true
      run: |
        echo "merged true"
    - name: License Plist
      run: |
        #!/bin/sh
        curl "https://api.github.com/repos/mono0926/LicensePlist/releases" \
             | jq -r '.[0].assets_url' \
             | xargs -n1 curl \
             | jq -r '.[0].browser_download_url' \
             | xargs -n1 curl -LOk
        ls -l 
        echo "---"
        unzip license-plist.zip
        if [ $? -ne 0 ]
        then
            echo "Filed to download the latest executable binary. Maybe the GitHub API limit occurs. Try other installation methods(see: https://github.com/mono0926/LicensePlist#installation )."
           exit 1
        fi
        #cp -f license-plist /usr/local/bin/license-plist
        ls -l
        echo "---"
        ./license-plist

